### ISSUE TITLE
Use of `service ... restart` commande instead of `systemctl restart ...`

### ISSUE THREAD

**Issue by audeoudh** [drakkar-lig/walt-python-packages#63]
https://github.com/drakkar-lig/walt-python-packages/blob/1bf1fe6a27252e922d2dd0210dc2b5a16ec78f89/server/walt/server/threads/main/network/dhcpd.py#L254

Here, you use `service` command not available on some new systems with systemd only and no init-equivalent bindings.

Moreover, [in the docs](https://github.com/drakkar-lig/walt-python-packages/blob/master/client/walt/client/doc/md/server-setup-from-fresh-debian.md#6--update-dhcpd-configuration), we suggest to use a systemd service for that unit.  Wouldn't `systemctl restart isc-dhcp-server.service` be better?

**Comment by eduble** [comment]
Sure.
walt was created before systemd so this sort of legacy code can exist.
